apiVersion: apps/v1
kind: Deployment
metadata:
  name: txt-report-frontend
  labels:
    app: txt-report-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: txt-report-frontend
  template:
    metadata:
      labels:
        app: txt-report-frontend
    spec:
      containers:
        - name: txt-report-frontend
          image: quay.io/sergio_canales_e/quarkus/txt-report-frontend:1.0.9
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTIONS
              value: "-Dquarkus.http.host=0.0.0.0"
            - name: FRONTEND_URL
              value: "http://txt-report-frontend-svc:8080"
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 1
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 2
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
