name: Publish Native Image

on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: Container image tag (defaults to pom version)
        required: false
  push:
    branches:
      - master

concurrency:
  group: publish-native-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: quay.io
  IMAGE_REPOSITORY: sergio_canales_e/quarkus/txt-report-frontend

jobs:
  publish:
    if: github.ref == 'refs/heads/master' || github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Ensure registry credentials for branch builds
        if: github.event_name == 'push'
        run: |
          if [ -z "${{ secrets.QUAY_USERNAME }}" ] || [ -z "${{ secrets.QUAY_PASSWORD }}" ]; then
            echo "Quay.io credentials are required when building from master." >&2
            exit 1
          fi

      - name: Resolve image tag
        id: meta
        run: |
          if [ -n "${{ github.event.inputs.image-tag }}" ]; then
            tag="${{ github.event.inputs.image-tag }}"
          else
            tag="$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)"
          fi
          echo "tag=$tag" >> "$GITHUB_OUTPUT"
          echo "Resolved image tag: $tag"

      - name: Determine push flag
        id: publish
        run: |
          if [ -n "${{ secrets.QUAY_USERNAME }}" ] && [ -n "${{ secrets.QUAY_PASSWORD }}" ]; then
            echo "push=true" >> "$GITHUB_OUTPUT"
          else
            echo "push=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Log in to Quay.io
        if: steps.publish.outputs.push == 'true'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Log in to Quay.io for Podman
        if: steps.publish.outputs.push == 'true'
        run: |
          set -euo pipefail
          echo "${{ secrets.QUAY_PASSWORD }}" | podman login "${{ env.REGISTRY }}" \
            --username "${{ secrets.QUAY_USERNAME }}" --password-stdin

      - name: Build native executable and container image
        env:
          PUSH_IMAGE: ${{ steps.publish.outputs.push }}
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
        run: |
          set -euo pipefail

          MAVEN_ARGS=(
            "-B" "-ntp" "clean" "package"
            "-Dquarkus.package.type=native"
            "-Dquarkus.native.container-build=true"
            "-Dquarkus.native.container-runtime=docker"
            "-Dquarkus.container-image.builder=docker"
            "-Dquarkus.container-image.build=true"
            "-Dquarkus.container-image.registry=${REGISTRY}"
            "-Dquarkus.container-image.group=${IMAGE_REPOSITORY%/*}"
            "-Dquarkus.container-image.name=${IMAGE_REPOSITORY##*/}"
            "-Dquarkus.container-image.tag=${{ steps.meta.outputs.tag }}"
            "-Dquarkus.container-image.push=${PUSH_IMAGE}"
          )

          if [ "${PUSH_IMAGE}" = "true" ]; then
            MAVEN_ARGS+=(
              "-Dquarkus.container-image.username=${QUAY_USERNAME}"
              "-Dquarkus.container-image.password=${QUAY_PASSWORD}"
            )
          fi

          ./mvnw "${MAVEN_ARGS[@]}"
