name: Build and Deploy Quarkus App

on:
  push:
    tags:
      - 'v*'
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Validate version matches tag
        run: |
          TAG_NAME="${GITHUB_REF##*/}"
          POM_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          if [[ "$TAG_NAME" != "v$POM_VERSION" ]]; then
            echo "❌ Tag version '$TAG_NAME' does not match pom.xml version 'v$POM_VERSION'"
            exit 1
          fi
          echo "✅ Tag matches pom.xml version: $TAG_NAME"

      - name: Build Quarkus Application
        run: mvn clean package -DskipTests

      - name: Deploy to GitHub Packages
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
